CREATE TABLE DEPT_TCL AS SELECT * FROM DEPT;

INSERT INTO DEPT_TCL VALUES (50, 'DATABASE', 'SEOUL');
COMMIT;

SELECT * FROM DEPT_TCL;
ROLLBACK;

-- 하나의 트랜젝션 생성
INSERT INTO DEPT_TCL VALUES (60, 'NETWORK', 'BUSAN');
UPDATE DEPT_TCL SET LOC = 'SEOUL' WHERE DEPTNO = 40;
DELETE FROM DEPT_TCL WHERE DNAME = 'RESERACH' ;
SELECT * FROM DEPT_TCL;

COMMIT;